name: 'MC Status Card'
description: 'Minecraft status card powered entirely by GitHub'
author: 'ppodds'
inputs:
  host:
    required: true
    description: 'MC Server host'
  port:
    required: false
    description: 'MC Server port'
    default: '25565'
  bgImage:
    required: false
    description: 'background image url'
    default: ''
runs:
  using: 'composite'
  steps:
    - run: run.sh
      shell: bash
      env:
        INPUTS: ${{ toJson(inputs) }}
