name: Release
on:
  release:
    types: [published, edited]

jobs:
  docker:
    runs-on: ubuntu-latest
    name: 'Build Docker image and push to Docker Hub'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ppodds/mc-status-card:latest
  test:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          host: mp.mc-complex.com
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
  release-note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ppodds/release-note@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
